# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Development Build and Test

on:
  push:
    branches: [ dev ]
  #pull_request:
    #branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./wingit

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: |
            mvn -B test -P dev 



  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./wingit

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
            mvn -B package -P dev --file pom.xml
            mkdir artifacts && cp target/*.jar artifacts
            cd artifacts && ls

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: ./wingit/artifacts
