# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build and Deploy

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # Below I don't think we are using it. Was from template.
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run:
            cd wingit
            mvn -B package -P prod --file pom.xml
            mkdir artifacts && cp target/*.jar artifacts
            cd artifacts && ls

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: artifacts

    # TODO: Deployment step to AWS.

    # Below is also from the template though our deployment will be for AWS to be set up later.
    #- name: Publish to GitHub Packages Apache Maven
      #run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      #env:
        #GITHUB_TOKEN: ${{ github.token }}
